#index:
#    path: /
#    controller: App\Controller\DefaultController::index
_liip_imagine:
  resource: "@LiipImagineBundle/Resources/config/routing.yaml"
forward:
  path: /{asda}
  controller: App\Controller\ForwardController::forwardToIndex
  requirements:
      asda: ^(?!(api|files)|_(profiler|wdt)).*
index:
  path: /
  controller: App\Controller\RootController::index
  methods:    GET|HEAD
root:
  path: /api
  controller: App\Controller\RootController::home
  methods:    GET|HEAD
rootDB:
  path: /api/db
  controller: App\Controller\RootController::initDB
  methods:    GET|HEAD
homepage:
  path: /api/home
  controller: App\Controller\HomeController::home
  methods:    GET|HEAD
cennik:
  path: /api/cennik
  controller: App\Controller\OtherController::cennik
  methods:    GET|HEAD
cennikCat:
  path: /api/cennik/categories
  controller: App\Controller\OtherController::getCategories
  methods:    GET|HEAD
kontakt:
  path: /api/kontakt
  controller: App\Controller\OtherController::kontakt
  methods:    GET|HEAD
sendMessage:
  path: /api/kontakt
  controller: App\Controller\OtherController::postMessage
  methods:    POST
preparaty:
  path: /api/preparatytrychologiczne
  controller: App\Controller\OtherController::preparaty
  methods:    GET|HEAD
omnie:
  path: /api/omnie
  controller: App\Controller\OtherController::omnie
  methods:    GET|HEAD
trichoskopia:
  path: /api/trichoskopia
  controller: App\Controller\OtherController::trichoskopia
  methods:    GET|HEAD
problem:
  path: /api/problem/{name}
  controller: App\Controller\ProblemController::show
  methods:    GET|HEAD
zabiegList:
  path: /api/zabieg
  controller: App\Controller\ZabiegController::showAllCategories
  methods:    GET|HEAD
zabiegByCat:
  path: /api/zabieg/{category}
  controller: App\Controller\ZabiegController::showByCategory
  methods:    GET|HEAD
zabiegByName:
  path: /api/zabieg/{category}/{name}
  controller: App\Controller\ZabiegController::showByName
  methods:    GET|HEAD
api_login:
  path: /api/login
  controller: App\Controller\LoginController::login
  methods: POST
logout:
  path: /api/logout
register:
  path: /api/register
  controller: App\Controller\LoginController::register
  methods:    POST
user:
  path: /api/user
  controller: App\Controller\LoginController::user
  methods: GET|HEAD
file:
  path: /files/{dirname}/{filename}
  controller: App\Controller\StorageController::getFile
  methods:    GET|HEAD
#POST MAPPINGI + ADMINISTRACYJNE PANELE
postfile:
  path: /files/uploadfile/{dirname}
  controller: App\Controller\StorageController::postFile
  methods:    POST
admin:
  path: /api/admin
  controller: App\Controller\Admin\AdminController::getAdmin
  methods:    GET|HEAD
admincennik:
  path: /api/admin/cennik
  controller: App\Controller\Admin\AdminController::postCennik
  methods:    POST
adminkontakt:
  path: /api/admin/kontakt
  controller: App\Controller\Admin\AdminController::postKontakt
  methods:    POST
adminkontaktget:
  path: /api/admin/kontakt
  controller: App\Controller\Admin\AdminController::getKontakt
  methods:    GET|HEAD
adminslideshow:
  path: /api/admin/slideshow
  controller: App\Controller\Admin\AdminController::postSlideshow
  methods:    POST
adminslideshowget:
  path: /api/admin/slideshow
  controller: App\Controller\Admin\AdminController::getSlideshow
  methods:    GET|HEAD
adminproblem:
  path: /api/admin/problem
  controller: App\Controller\Admin\AdminController::postProblem
  methods:    POST
adminproza:
  path: /api/admin/proza
  controller: App\Controller\Admin\AdminController::postProza
  methods:    POST
adminzabieg:
  path: /api/admin/zabieg
  controller: App\Controller\Admin\AdminController::postZabieg
  methods:    POST
adminzabiegget:
  path: /api/admin/zabieg
  controller: App\Controller\Admin\AdminController::getZabieg
  methods:    GET|HEAD
adminmessages:
  path: /api/admin/message
  controller: App\Controller\Admin\AdminController::getMessages
  methods:    GET|HEAD
