<?php


namespace App;


use Symfony\Bundle\FrameworkBundle\HttpCache\HttpCache;

class CacheKernel extends HttpCache
{
    protected function getOptions()
    {
        return parent::getOptions(); // TODO: Change the autogenerated stub
    }

}